import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const hedvigSans = localFont({
	src: "./fonts/Hedvig-Sans.woff2",
	variable: "--font-hedvig-sans",
	display: "swap",
});

const hedvigSerif = localFont({
	src: "./fonts/Hedvig-Serif.woff2",
	variable: "--font-hedvig-serif",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	other: {
		"font-preload": "true",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${hedvigSans.variable} ${hedvigSerif.variable}`}
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
